# Generated by Django 3.2.25 on 2024-07-27 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ColourProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ComboEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility_rate', models.IntegerField()),
                ('background_colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_combo_effect', to='combos.colour')),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_effect', to='combos.colour')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='combos.colourproject')),
            ],
        ),
    ]
